/** @format */

import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Layout from "@/components/Layout";
import Head from "next/head";
import { AuthContextProvider } from "@/lib/context/Auth/authContext";
import { useState } from "react";

export default function App({ Component, pageProps }: AppProps) {
  const [TicketSearch, setTicketSearch] = useState<string>("");
  interface IProps {
    ticketSearch: string;
    setTicketSearch: (value: string) => void;
  }
  const props: IProps = {
    ticketSearch: TicketSearch,
    setTicketSearch: setTicketSearch,
  };
  return (
    <AuthContextProvider>
      <Layout {...props}>
        <Head>
          <title>Mister Ticket</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
          <link rel="manifest" href="/site.webmanifest" />
          <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="theme-color" content="#ffffff" />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </AuthContextProvider>
  );
}
