/** @format */

import Head from "next/head";
import { GetServerSideProps } from "next";
import StripeCheckout from "../services/prisma/stripeCheckout";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StripeCheckout />
      </main>
    </>
  );
}
