/** @format */

import Head from "next/head";
import { GetServerSideProps } from "next";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [ticketSearch, setTicketSearch] = useState<string>("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={`/ticket/05c4af58-389d-408b-a017-6725d4b97766`}>
          see ticket
        </Link>
      </main>
    </>
  );
}
