/** @format */

import Head from "next/head";
import StripeCheckout from "@/services/stripe/stripeCheckout";
import { GetServerSideProps } from "next";

interface IPageProps {
  ticketId?: string
}

const Home: React.FC<IPageProps> = ({
  ticketId
}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StripeCheckout />
      </main>
    </>
  );
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  const ticketId = context.query.ticketId as string
  if (!ticketId) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      ticketId: ticketId
    },
  }
}
