# @format

name: "Test & Build"
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: install dependencies of cdk
        run: yarn
        working-directory: aws-cdk
      - name: install dependencies
        run: yarn
        working-directory: /
      - name: build-nextjs
        run: yarn build
